version: '3.5'

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/productiondb --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    environment:
      MONGO_INITDB_ROOT_USERNAME: blacksea
      MONGO_INITDB_ROOT_PASSWORD: blacksea
      MONGO_INITDB_DATABASE: reactiveSpringExample
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: blacksea
      ME_CONFIG_MONGODB_ADMINPASSWORD: blacksea
  app:
    build: .
    ports:
      - "8080:8080"
    links:
      - mongo-express
      - mongo
    depends_on:
      mongo:
        condition: service_healthy